// Generates worker/src/seed.ts from ../recipes/*.json so first-party recipes
// are bundled into the Worker and can seed an empty KV namespace.
// Runs automatically before dev/build/deploy/typecheck.
import { readdirSync, readFileSync, writeFileSync, mkdirSync, existsSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const recipesDir = resolve(here, "../../recipes");
const outFile = resolve(here, "../src/seed.ts");

const recipes = [];
if (existsSync(recipesDir)) {
  for (const file of readdirSync(recipesDir).filter((f) => f.endsWith(".json")).sort()) {
    try {
      const json = JSON.parse(readFileSync(join(recipesDir, file), "utf8"));
      if (json && typeof json === "object" && Array.isArray(json.tools)) {
        if (!json.id) json.id = file.replace(/\.json$/, "");
        recipes.push(json);
      } else {
        console.warn(`[gen-seed] skipping ${file}: not a recipe object`);
      }
    } catch (err) {
      console.warn(`[gen-seed] skipping ${file}: ${err.message}`);
    }
  }
}

mkdirSync(dirname(outFile), { recursive: true });
writeFileSync(
  outFile,
  `// AUTO-GENERATED by scripts/gen-seed.mjs from ../recipes/*.json — do not edit.
import type { Recipe } from "@webmcp-anywhere/shared";

export const SEED_RECIPES: Recipe[] = ${JSON.stringify(recipes, null, 2)};
`,
);
console.log(`[gen-seed] wrote ${recipes.length} recipe(s) to src/seed.ts`);
